language: perl
perl:
  - "5.8"
  - "5.8-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20-thr"
  - "blead"
matrix:
  include:
    - perl: "5.18"
      env: AUTHOR_TESTING=0
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - '[ "$AUTHOR_TESTING" != 0 ] && cpan-install SQL::Abstract::Test || true'
